sudo: required

services:
  - docker

before_install:
  # Stops the local instance of Postgres.
  - sudo /etc/init.d/postgresql stop
  
  # Checks which Docker containers are running for debug purposes.
  - docker ps

  # Starts the test Postgres server within a Docker container.
  - cd sqlg-testdb-postgres && ./start.sh

language: java

jdk:
  - oraclejdk8

script:
  - sudo rm /etc/mavenrc
  - export MAVEN_OPTS="-Djava.security.egd=file:/dev/./urandom -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmx5012m"
  - mvn -e -T40 test

notifications:
  email:
    recipients:
      - pieter.martin@riseup.net
    on_success: always
    on_failure: always
